# VM 1 host configuration and installation
---

- name: Install "Grafana" necessary packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - software-properties-common
    - wget

- name: Create Grafana gpg key directory
  file:
    path: /etc/apt/keyrings/
    state: directory

- name: Download, convert and store the grafana key
  shell: "wget -q -O - https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /etc/apt/keyrings/grafana.gpg > /dev/null"
  ignore_errors: yes

- name: Add Grafana repository
    shell: "echo deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main | sudo tee -a /etc/apt/sources.list.d/grafana.list"

- name: Install Grafana
    apt:
      name: grafana
      state: present
      update_cache: yes

- name: Install "Prometheus"
  apt:
    name: prometheus
    state: present

- name: Start Grafana and Prometheus services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items: 
    - grafana-server
    - prometheus